version: '3.7'
services:
  web:
    restart: on-failure
    build: .
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start
    depends_on:
      - postgres
  postgres:
    image: postgres:11-alpine
    container_name: PostgresDB
    restart: always
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=compulsive
      - POSTGRES_PASSWORD=secret
    volumes:
      - /var/db/data/postgresql:/var/lib/postgresql
