version: '3.7'
services:
  frontend:
    image: compulsivecoders
    build: ./frontend
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/frontend
    environment:
      - BASE_URL=http://api:3001
    command: yarn dev
    depends_on:
      - api
  api:
    image: compulsivecoders-api
    build: ./api
    ports:
      - "3001:3001"
    volumes:
      - ./api:/usr/src/api
    environment:
      - BASE_URL=test
      - DB_NAME=postgres
      - DB_HOSTNAME=192.168.64.3
      - DB_USERNAME=compulsive
      - DB_PASSWORD=secret
      - DB_PORT=54320
    command: yarn start
    depends_on:
      - postgres
  postgres:
    image: postgres:11-alpine
    container_name: PostgresDB
    restart: always
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=compulsive
      - POSTGRES_PASSWORD=secret
    volumes:
      - /var/db/data/postgresql:/var/lib/postgresql
